# Generated by Django 5.2 on 2026-08-17 07:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('deptid', models.AutoField(primary_key=True, serialize=False)),
                ('deptname', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empid', models.CharField(max_length=20)),
                ('empname', models.CharField(max_length=100)),
                ('empemail', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('emppassword', models.CharField(max_length=100)),
                ('empdiscription', models.CharField(max_length=100)),
                ('joindate', models.DateField(default=datetime.date.today)),
                ('pictures', models.ImageField(default='images/default.jpg', upload_to='profileimg/')),
                ('empdept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.department')),
            ],
        ),
    ]
