# Generated by Django 5.2 on 2026-08-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emppassword',
        ),
    ]
