# Generated by Django 5.2 on 2026-08-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0002_remove_employee_emppassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('subject', models.TextField(blank=True)),
                ('file_attachment', models.FileField(blank='True', null='True', upload_to='file')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('current_holder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_holder', to='adminapp.employee')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intiated_files', to='adminapp.employee')),
            ],
        ),
    ]
