# Generated by Django 5.2 on 2026-08-20 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_employee_emppassword'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('FORWARD', 'Forward'), ('RETURN', 'Return'), ('CLOSE', 'Close')], max_length=20)),
                ('remark', models.TextField(blank=True)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='userapp.files')),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_files', to='adminapp.employee')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_files', to='adminapp.employee')),
            ],
            options={
                'ordering': ['moved_at'],
            },
        ),
    ]
